/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unicamp.ft.ui;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import br.unicamp.ft.dados.PaisesDados;
import br.unicamp.ft.entities.AnosPaises;

/**
 *
 * @author leo
 */
public class Tabela2 extends javax.swing.JFrame {

    /**
     * Creates new form Tabela2
     */
    public Tabela2(PaisesDados fert, int anoInicial,int anoFinal) {
        initComponents();
        jTable1.setModel(new ConsumoFertilizante(fert,anoInicial,anoFinal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

class ConsumoFertilizante extends AbstractTableModel{
    List anos;
    PaisesDados fert;
    
    public ConsumoFertilizante(PaisesDados fert,int from,int to){
        this.fert = fert;
        anos = fert.anos(from, to);
    }

    @Override
    public int getRowCount() {
        return anos.size();
    }

    @Override
    public int getColumnCount() {
        return 2;
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        if (columnIndex == 0) 
            return anos.get(rowIndex);
        else {
            return fert.valor((int) anos.get(rowIndex));
        }
    }
    @Override
    public String getColumnName(int colIndex) {
        return colIndex == 0 ? "Ano" : "Consumo" ;
    }
    
    @Override
    public Class getColumnClass(int colIndex) {
        return Integer.class;
    }
}
